version: '3.4'

services:
  catalog.db:
    image: mongo:6.0.3
    
  cart.db:
    image: redis:7.0.5-alpine
    
  discount.db:
    image: postgres:15.1-alpine
    
  pgadmin:
    image: dpage/pgadmin4:6.16
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      
  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Services/Cart/Cart.API/Dockerfile
      
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile