version: '3.4'

services:
  catalog.db:
    container_name: catalog.db
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"
  
  cart.db:
    container_name: cart.db
    restart: always
    ports:
      - "6379:6379"
  
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalog.db:27017"
    ports:
      - "8000:80"
    depends_on:
      - catalog.db
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        
  cart.api:
    container_name: cart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=cart.db:6379"
    depends_on:
      - cart.db
    ports:
      - "8001:80"